continue-on-errorの条件追加

diff --git a/.github/workflows/front-github-actions.yml b/.github/workflows/front-github-actions.yml
--- a/.github/workflows/front-github-actions.yml
+++ b/.github/workflows/front-github-actions.yml
@@ -19,8 +19,9 @@ jobs:
         run: npm ci
       - name: ESLint
         run: npm run check:eslint
-      - name: Prettier
-        run: npm run check:prettier
+      - name: Prettier (Warning Only)
+        run: npm run check:prettier || echo "Prettier check failed, but continuing..."
+        continue-on-error: true
       - name: build
         run: npm run build
 
